services:
  leekbot:
    image: leekbot:latest
    networks:
      - database-connection
    secrets:
      - discord-token
    entrypoint: [ '/bin/sh', '-c', 'export DISCORD_TOKEN=$$(/run/secrets/discord-token) ; source /entrypoint.sh']

    #  mongo:
    #    image: mongo:latest
    #    ports:
    #      - '8000:27017'
    #    volumes:
    #      - leekdb-data:/data/db
    #    networks:
    #      - database-connection

volumes:
  leekdb-data: {}

networks:
  database-connection: {}

secrets:
  discord-token:
    file: .discord_secret
